FROM resin/raspberrypi3-debian:latest

RUN apt-get update && apt-get install -yq \
  python3 \
  python3-sense-hat \
  python3-pip \
  wget && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY ./requirements.txt /requirements.txt

RUN pip3 install -r /requirements.txt

COPY . ./

ENV INITSYSTEM on

CMD ["python3", "main.py"]